
label prologo1:

MC: Ahhhh Ahhhh AHHHH
MC: ya no más… Por favor… Ya no más…
MC: Ya basta… YA BASTA
MC se encuentra derrumbado… envolviéndose a si mismo entre sus brazos para sentir algo de confort… 
 Tanto el clima como el lugar son simplemente tan difíciles de explicar, que solo una palabra la podría describir, infierno…
No es el infierno que las obras que la describen como un escenario dantesco o demoniaco lleno de criaturas que rebasan a la palabra horripilante…
Sino simplemente en un limbo… oscuro… inhóspito… silencioso…
Uno que, tras ser empujado a sufrirlo por una cantidad casi infinita de tiempo, volvería loco a cualquiera 
MC se compadece mientras sus lágrimas brotan como si de ríos se tratasen
MC: ya... Basta por favor…
MC: Estoy cansado…
MC: Demasiado…
MC lanza un pedido de auxilio que se pierde en el vacío infinito en el que se encuentra.
MC: He repetido esas mismas escenas miles de veces…
MC: No puedo aguantar más…
MC: Sayori…
(Aquí aparecen flashbacks de la muerte de Sayori)
MC: Natsuki:…
MC: Yuri…
(Aquí aparecen flashback de alguna muerte de Natsuki, quizá de Exit Music)
MC: Monika...
(Una muerte de Monika o quizá algo malo que haya hecho ella)
MC: todas han sido empujadas a…
MC: A acabar con sus vidas, y con las de los demás…
MC: ¿Porque?...
MC: Estaban bien, ESTABAN BIEN…
MC: yo… Yo las intenté salvar…
MC: ¿Que hice mal?
MC buscaba en su memoria, sin embargo a su mente llegaban recuerdos dolorosos, que haciendo que su corazón ya destrozado, se mortificara cada vez más por los errores del pasado
(Aquí pueden haber flashbacks de mods con ruta mala que provocaran sus muertes)
MC: todas esas veces…
MC: todas esas elecciones
MC: todas esas conclusiones…
MC: soy el culpable de que todo esto acabara así…
MC: 15420…
MC: han sido ya…15420 reseteos…
MC: Y sigo cometiendo los mismos errores
MC: no puedo aprender…
MC: No puedo recordar
MC: No puedo existir realmente hasta que regreso a este lugar…
(Tiempo de unos segundos)

MC: Yo… solo quiero liberarlas…
MC: Librarlas de ese fatídico destino…
MC: Es tanto pedir…
Se escucha una melodía… Es dulce, pacifica… 
MC olvida todos sus pesares por unos segundos… se siente en trance. Como si esta lo transportase a un lugar diferente
MC: Ahh…
MC: Es hermoso…
MC: Primavera…
MC: brisa…
MC: pájaros revoloteando…
MC: cielo despejado…
MC: ¿Chicas, pueden verlo?
MC: Chicas, lo ven… ¿verdad?
En un instante, empiezo a notar un cuerpo que se acerca a mí lentamente
Parece el de una mujer
MC: Monika?
MC: ¿Monika, eres tú?
Logro notar exactamente el momento en el que el cuerpo abre la boca para hablar
Voz misteriosa: No… Lo siento, pero la que llamas Monika no existe, aun
Voz misteriosa: He oído tú pedido...
MC se queda observándola, tratando de distinguir su rostro
Voz misteriosa: ¿Quieres liberarlas, no?
MC: Eh?
MC se queda pasmado… Sin entender lo que está pasando… Ni en donde esta 
Ni quien es este ser…
Voz misteriosa: Hay una manera de que puedas arreglarlo
Lo único que puede hacer es responder
MC: Yo…
MC: Solo quiero salir y poder terminar con esto, con todo el sufrimiento del club.
MC: Quiero liberarlas del yugo de sus desgracias
MC: Quiero que puedan salir de este círculo que solo las lleva a morir, una y otra…otra y otra vez.
Voz misteriosa: Bien, parece que esas palabras eran en serio
MC con una voz temblorosa pregunta
MC: ¿A que te refieres?
 Voz misteriosa: Es posible, tener una realidad en la que ellas sean libres, incluido tú. 
Voz misteriosa: Sin embargo, tendrás un tiempo limitado; por lo que regresarás con tus recuerdos
Voz misteriosa: Pero para ello, tienes que pasar por un sufrimiento inigualable, ya que no estas hecho para mantener tus recuerdos tras el reseteo. 
Voz misteriosa: No obstante, solo así podrás tener una oportunidad de lograr tu cometido
MC: …
MC: ¿qué clase de dolor?
Voz misteriosa: Pues en resumidas cuentas, sentirás que tus entrañas se retuercen, mientras que tú cerebro sufrirá como si agujas atravesaran cada parte. Aunque no estoy segura del todo…
MC traga saliva, mientras trata de asimilar lo que le va a pasar de aceptar la propuesta de la entidad que tiene en frente
Sabe que no tiene más alternativa que hacer lo que dice para lograr su anhelado deseo
MC: Brillante…
Voz misteriosa: eh?
MC: es sol detrás de ti es brillante, parece que va a atardecer
Mc mira al cielo por unos segundos… luego cierra los ojos mientras siente la brisa por última vez 
Voz misteriosa: Ya veo…
Voz misteriosa: La vida es dura con mucha gente…
Voz misteriosa: Y a veces, para salir de ello se lanzan a sí mismo a un infierno con tal de obtener paz
Voz misteriosa: Dime mc, ¿estás dispuesto a hacer lo que sea por esa paz?
Chicas, es tiempo de expiar mis pecados… Sayori… Natsuki…Yuri…Monika…
Es tiempo de que finalmente sean libres…
MC: Si, LO ESTOY
Voz misteriosa: De acuerdo… (5:06)
Voz misteriosa: entonces, toma mi mano
Voz misteriosa: Una vez que lo hagas, empezarás nuevamente
MC mira por un instante la mano de la chica
Su corazón está que late cada vez más fuerte, esto es lo que ha estado buscando por tanto tiempo…
Sin más, estrecha su mano con la de la entidad …
Voz misteriosa: Adiós, (player)
"Mi espalda, se siente como si esta pesara un montón, la figura ha desaparecido, y con ella a su vez el bello paisaje del ocaso
Cierro los ojos, esperando el momento en el que todo empiece
(Sonido de una espada atravesando carne)
Mc: AHHHHHHHHHHHHHHHHHHHH!
MC suelta un estruendoso alarido, no quiere abrir sus ojos por el miedo que significa ver la gravedad del daño recibido, sin embargo decide que no tiene más opción que hacerlo…
¡Agujero en todo mi estómago! Mi cuerpo fue atravesado por una espada
Duele… 
No más dolor, por favor
NO MÁS
Al momento una daga hace lo propio con mi mano izquierda
¿DE DONDE VIENEN? ¿NO LAS PUEDO ESQUIVAR?
Uno a uno, numerosas armas se clavan en cada parte de mí ser
AHHHHHHHHH
Mis brazos, se desprenden
SANGRE… SANGRE A POR MONTÓN
NO QUIERO VER
POR FAVOR NO QUIERO MÁS
AHHHHHHHHHHHHH
VA ATRAVES DE MI CEREBRO
NO NO, NO MÁS
MI CABEZA DUELE
AHHHHHHHHHH 
La desesperación invade la cabeza de MC
QUIERO HUIR
NO PUEDO 

MC: … NO QUIERO ABRIR OTRA VEZ LA PUERTA…
MC: SAYORI…
MC: MI MEJOR AMIGA… ELLA ESTA… ELLA ESTA MUERTA
MC: AHHHHHH MI CABEZAAAAAAAAA

MC: POR FAVOR, NATSUKI… LEVANTATE…
MC: ….ELLA… ELLA ESTA FRIA…
MC: YO REALMENTE LA QUERIA
MC: Y NO PUDE HACER NADA
YO DEBO SOPORTARLO POR EL BIEN DE ELLAS

MC: ESTAS PALIDA…
MC: ROJO… AHORA ESTA TEÑIDO DE ROJO
MC: MONIKA… REGRESA…
MC: LO SIENTO… ¡LOS SIENTO!
AUN PUEDO MOVERME
MC: Aun si perdiera las piernas, seguiré avanzando… 
AUN PUEDO SEGUIR ADELANTE 
MC: Por la gente que aprecio, este dolor aguantaré
AUN TENGO QUE SOLUCIONAR LAS COSAS
MC: Chicas, yo las liberaré…
MC: ESTA ES… MI ULTIMA OPORTUNIDAD…